---
- name: install/enable daemon service
  hosts: allPi
  tasks:
  - name: write config file of service
    template: src=templates/asn_daemon.service.j2 dest=/etc/systemd/system/asn_daemon.service

  - name: load and enable service
    systemd:
      name: asn_daemon
      enabled: yes
      state: restarted
      daemon_reload: yes
