---
- name: disable internet forwarding on clients
  hosts: allPi
  tasks:
  - name: check if route exists
    command: ip route list
    register: route_list

  - name: remove route
    command: ip route del default
    when: route_list.stdout.find('default') != -1

- name: disable internet forwarding on server
  hosts: server
  tasks:
  - name: check if rules exist
    command: iptables -t nat -C POSTROUTING -o {{server_internet_interface_name}} -j MASQUERADE
    register: rule_check
    failed_when: false
  - name: remove masquerade nat-rule
    command: iptables -t nat -D POSTROUTING -o {{server_internet_interface_name}} -j MASQUERADE
    when: rule_check.stderr.find('No chain/target/match by that name') == -1
  - name: remove ingoing filter-rule
    command: iptables -D FORWARD -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
    when: rule_check.stderr.find('No chain/target/match by that name') == -1
  - name: remove outgoing filter-rule
    command: iptables -D FORWARD -o {{server_internet_interface_name}} -i {{server_adhoc_interface_name}} -s 10.1.1.0/24 -m conntrack --ctstate NEW -j ACCEPT
    when: rule_check.stderr.find('No chain/target/match by that name') == -1
  - name: disable ipv4 traffic forwarding
    command: sysctl net.ipv4.ip_forward=0
