---
- name: enable internet forwarding on server
  hosts: server
  tasks:
  - name: enable ipv4 traffic forwarding
    command: sysctl net.ipv4.ip_forward=1
  - name: check if rules exist
    command: iptables -t nat -C POSTROUTING -o {{server_internet_interface_name}} -j MASQUERADE
    register: rule_check
    failed_when: false
  - name: add outgoing filter-rule
    command: iptables -A FORWARD -o {{server_internet_interface_name}} -i {{server_adhoc_interface_name}} -s 10.1.1.0/24 -m conntrack --ctstate NEW -j ACCEPT
    when: rule_check.stderr.find('No chain/target/match by that name') != -1
  - name: add ingoing filter-rule
    command: iptables -A FORWARD -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
    when: rule_check.stderr.find('No chain/target/match by that name') != -1
  - name: add masquerade nat-rule
    command: iptables -t nat -A POSTROUTING -o {{server_internet_interface_name}} -j MASQUERADE
    when: rule_check.stderr.find('No chain/target/match by that name') != -1

- name: enable internet forwarding on clients
  hosts: allPi
  tasks:
  - name: check if route exists
    command: ip route list
    register: route_list

  - name: add route for internet forwarding
    command: ip route add default via 10.1.1.254
    when: route_list.stdout.find('default') == -1
