---
- name: reset all server iptables
  hosts: server
  tasks:
  - name: disable ipv4 traffic forwarding
    command: sysctl net.ipv4.ip_forward=0

  - name: reset filter table (default chains)
    command: iptables -F
  - name: reset filter table (user chains)
    command: iptables -X
  - name: reset nat table (default chains)
    command: iptables -t nat -F
  - name: reset nat table (user chains)
    command: iptables -t nat -X
  - name: reset mangle table (default chains)
    command: iptables -t mangle -F
  - name: reset mangle table (user chains)
    command: iptables -t mangle -X
  - name: reset raw table (default chains)
    command: iptables -t raw -F
  - name: reset raw table (user chains)
    command: iptables -t raw -X
  - name: reset security table (default chains)
    command: iptables -t security -F
  - name: reset security table (user chains)
    command: iptables -t security -X
  - name: reset default action (input)
    command: iptables -P INPUT ACCEPT
  - name: reset default action (forward)
    command: iptables -P FORWARD ACCEPT
  - name: reset default action (output)
    command: iptables -P OUTPUT ACCEPT
