---
- name: update network config files
  hosts: server
  tasks:
  - name: write network interfaces config (3 interfaces)
    template: src=templates/server/interfaces.j2 dest=/etc/network/interfaces
    when: server_ethernet_interface_name != ""

  - name: write network interfaces config (2 interfaces)
    template: src=templates/server/interfaces_no_ethernet.j2 dest=/etc/network/interfaces
    when: server_ethernet_interface_name == ""

  - name: write hostname config
    template: src=templates/server/hostname.j2 dest=/etc/hostname

  - name: write hosts config
    template: src=templates/server/hosts.j2 dest=/etc/hosts

- name: install packages
  hosts: server
  tasks:
  - name: "install/update apt packages: {{apt_packages_to_install}}"
    apt:
      name: "{{item}}"
      state: latest
      update_cache: yes
    with_items: "{{apt_packages_to_install}}"
    ignore_errors: yes
  - name: "install/update python packages: {{python_packages_to_install}}"
    pip: 
      name: "{{item}}"
      state: latest
    with_items: "{{python_packages_to_install}}"
    ignore_errors: yes

- name: generate ssh key
  hosts: server
  tasks:
  - name: create directory for ssh keys
    file: 
        path: /home/{{server_username}}/asn_server/ssh
        state: directory
        owner: "{{server_username}}"
        mode: "u=rwx,g=rwx,o=rwx"
  - name: generate ssh key pair
    user:
      name: "{{server_username}}"
      generate_ssh_key: yes
      ssh_key_file: /home/{{server_username}}/asn_server/ssh/id_rsa
