---
- name: update system time
  hosts: allPi
  tasks:
  - name: stop ntp service
    command: systemctl stop ntp
    ignore_errors: yes

  - name: update time
    command: ntpdate-debian
    ignore_errors: yes

  - name: start ntp service
    command: systemctl start ntp
    ignore_errors: yes
