# Here you want to list all your server ips. See the examples below.
# You should name them in a reasonable manner as to want to be able to pin down
# which node causes problem if there are any

# Set the ssh user in ./group_vars/fissionservers/settings.yml 

fissionservers:
  hosts:
    # server_2:
    #   ansible_host: "192.168.4.2"
    #   dispy_ip: "192.168.0.2"       # if you are installing over a different ip than you want to serve to
    # server_3:
    #   ansible_host: "192.168.4.3"
    server_30:
      ansible_host: "192.168.0.30"
    server_29:
      ansible_host: "192.168.0.29"
    server_28:
      ansible_host: "192.168.0.28"
    server_27:
      ansible_host: "192.168.0.27"

